export default [
  {
    Slot: "Back",
    Dungeon: "Ara-Kara, City of Echoes",
    BIS: true,
    class: "all",
  },
  { Slot: "Back", Dungeon: "The Stonevault", BIS: true, class: "warrior" },
  { Slot: "Back", Dungeon: "Grim Batol", BIS: false, class: "all" },
  { Slot: "Back", Dungeon: "Grim Batol", BIS: false, class: "all" },
  { Slot: "Back", Dungeon: "Grim Batol", BIS: false, class: "all" },
  {
    Slot: "Finger",
    Dungeon: "City of Threads",
    BIS: true,
    class: "shaman",
  },
  {
    Slot: "Finger",
    Dungeon: "The Dawnbreaker",
    BIS: false,
    class: "all",
  },
  {
    Slot: "Finger",
    Dungeon: "The Dawnbreaker",
    BIS: true,
    class: "DK",
  },
  {
    Slot: "Finger",
    Dungeon: "The Necrotic Wake",
    BIS: true,
    class: "shaman",
  },
  {
    Slot: "Finger",
    Dungeon: "The Necrotic Wake",
    BIS: false,
    class: "all",
  },
  {
    Slot: "Finger",
    Dungeon: "Siege of Boralus",
    BIS: false,
    class: "all",
  },
  {
    Slot: "Finger",
    Dungeon: "Siege of Boralus",
    BIS: false,
    class: "all",
  },
  { Slot: "Finger", Dungeon: "Grim Batol", BIS: false, class: "all" },
  { Slot: "Finger", Dungeon: "Grim Batol", BIS: true, class: "DK" },
  { Slot: "Finger", Dungeon: "Grim Batol", BIS: true, class: "warrior" },
  { Slot: "Finger", Dungeon: "Grim Batol", BIS: true, class: "warrior" },
  {
    Slot: "Neck",
    Dungeon: "City of Threads",
    BIS: true,
    class: "all",
  },
  { Slot: "Neck", Dungeon: "The Stonevault", BIS: true, class: "warrior" },
  {
    Slot: "Neck",
    Dungeon: "Mists of Tirna Scithe",
    BIS: false,
    class: "all",
  },
  {
    Slot: "Trinket",
    Dungeon: "Grim Batol",
    BIS: true,
    class: "shaman",
  },
  {
    Slot: "Trinket",
    Dungeon: "Mists of Tirna Scithe",
    BIS: true,
    class: "shaman",
  },
  {
    Slot: "Trinket",
    Dungeon: "Ara-Kara, City of Echoes",
    BIS: true,
    class: "DK",
  },
  {
    Slot: "Trinket",
    Dungeon: "The Necrotic Wake",
    BIS: true,
    class: "any",
  },
  {
    Slot: "Trinket",
    Dungeon: "The Stonevault",
    BIS: true,
    class: "warrior",
  },
  {
    Slot: "Trinket",
    Dungeon: "Ara-Kara, City of Echoes",
    BIS: true,
    class: "any",
  },
  {
    Slot: "Two Handed",
    Dungeon: "Mists of Tirna Scithe",
    BIS: true,
    class: "DK",
  },
  {
    Slot: "Two Handed",
    Dungeon: "Siege of Boralus",
    BIS: false,
    class: "DK",
  },
  { Slot: "Two Handed", Dungeon: "Grim Batol", BIS: true, class: "warrior" },
  {
    Slot: "Staff",
    Dungeon: "City of Threads",
    BIS: true,
    class: "shaman",
  },
  {
    Slot: "Staff",
    Dungeon: "The Stonevault",
    BIS: false,
    class: "shaman",
  },
  {
    Slot: "Staff",
    Dungeon: "Mists of Tirna Scithe",
    BIS: false,
    class: "shaman",
  },
  { Slot: "Staff", Dungeon: "Grim Batol", BIS: false, class: "shaman" },
  {
    Slot: "One Handed",
    Dungeon: "Ara-Kara, City of Echoes",
    BIS: true,
    class: "shaman",
  },
  {
    Slot: "One Handed",
    Dungeon: "City of Threads",
    BIS: false,
    class: "shaman",
  },
  {
    Slot: "One Handed",
    Dungeon: "Grim Batol",
    BIS: false,
    class: "shaman",
  },
  {
    Slot: "One Handed",
    Dungeon: "Mists of Tirna Scithe",
    BIS: false,
    class: "shaman",
  },
  {
    Slot: "Shield",
    Dungeon: "City of Threads",
    BIS: false,
    class: "shaman",
  },
  {
    Slot: "Shield",
    Dungeon: "The Stonevault",
    BIS: false,
    class: "shaman",
  },
  {
    Slot: "Shield",
    Dungeon: "Mists of Tirna Scithe",
    BIS: false,
    class: "shaman",
  },
  {
    Slot: "Shield",
    Dungeon: "The Necrotic Wake",
    BIS: true,
    class: "shaman",
  },
  {
    Slot: "Head",
    Dungeon: "Ara-Kara, City of Echoes",
    BIS: false,
    class: "shaman",
  },
  {
    Slot: "Head",
    Dungeon: "Mists of Tirna Scithe",
    BIS: false,
    class: "shaman",
  },
  {
    Slot: "Head",
    Dungeon: "The Necrotic Wake",
    BIS: false,
    class: "shaman",
  },
  { Slot: "Head", Dungeon: "Grim Batol", BIS: true, class: "shaman" },
  {
    Slot: "Shoulders",
    Dungeon: "The Dawnbreaker",
    BIS: false,
    class: "shaman",
  },
  {
    Slot: "Shoulders",
    Dungeon: "Mists of Tirna Scithe",
    BIS: true,
    class: "shaman",
  },
  {
    Slot: "Shoulders",
    Dungeon: "The Necrotic Wake",
    BIS: false,
    class: "shaman",
  },
  {
    Slot: "Shoulders",
    Dungeon: "Grim Batol",
    BIS: false,
    class: "shaman",
  },
  {
    Slot: "Chest",
    Dungeon: "City of Threads",
    BIS: false,
    class: "shaman",
  },
  {
    Slot: "Chest",
    Dungeon: "The Stonevault",
    BIS: false,
    class: "shaman",
  },
  {
    Slot: "Chest",
    Dungeon: "The Dawnbreaker",
    BIS: true,
    class: "shaman",
  },
  {
    Slot: "Wrist",
    Dungeon: "City of Threads",
    BIS: false,
    class: "shaman",
  },
  {
    Slot: "Wrist",
    Dungeon: "Mists of Tirna Scithe",
    BIS: false,
    class: "shaman",
  },
  {
    Slot: "Wrist",
    Dungeon: "Siege of Boralus",
    BIS: true,
    class: "shaman",
  },
  {
    Slot: "Hands",
    Dungeon: "Ara-Kara, City of Echoes",
    BIS: true,
    class: "shaman",
  },
  {
    Slot: "Hands",
    Dungeon: "The Stonevault",
    BIS: false,
    class: "shaman",
  },
  {
    Slot: "Waist",
    Dungeon: "City of Threads",
    BIS: false,
    class: "shaman",
  },
  {
    Slot: "Waist",
    Dungeon: "The Stonevault",
    BIS: false,
    class: "shaman",
  },
  {
    Slot: "Waist",
    Dungeon: "Mists of Tirna Scithe",
    BIS: false,
    class: "shaman",
  },
  {
    Slot: "Waist",
    Dungeon: "Siege of Boralus",
    BIS: true,
    class: "shaman",
  },
  {
    Slot: "Legs",
    Dungeon: "City of Threads",
    BIS: true,
    class: "shaman",
  },
  {
    Slot: "Legs",
    Dungeon: "The Necrotic Wake",
    BIS: false,
    class: "shaman",
  },
  {
    Slot: "Legs",
    Dungeon: "Siege of Boralus",
    BIS: false,
    class: "shaman",
  },
  {
    Slot: "Feet",
    Dungeon: "Ara-Kara, City of Echoes",
    BIS: false,
    class: "shaman",
  },
  {
    Slot: "Feet",
    Dungeon: "The Dawnbreaker",
    BIS: true,
    class: "shaman",
  },
  {
    Slot: "Feet",
    Dungeon: "The Necrotic Wake",
    BIS: false,
    class: "shaman",
  },
  {
    Slot: "Feet",
    Dungeon: "Siege of Boralus",
    BIS: false,
    class: "shaman",
  },
  { Slot: "Feet", Dungeon: "Grim Batol", BIS: false, class: "shaman" },
  { Slot: "Feet", Dungeon: "Grim Batol", BIS: false, class: "shaman" },
  {
    Slot: "Head",
    Dungeon: "The Dawnbreaker",
    BIS: true,
    class: "DK",
  },
  {
    Slot: "Head",
    Dungeon: "Mists of Tirna Scithe",
    BIS: true,
    class: "warrior",
  },
  {
    Slot: "Head",
    Dungeon: "The Necrotic Wake",
    BIS: false,
    class: "plate",
  },
  {
    Slot: "Shoulders",
    Dungeon: "Ara-Kara, City of Echoes",
    BIS: true,
    class: "DK",
  },
  {
    Slot: "Shoulders",
    Dungeon: "City of Threads",
    BIS: false,
    class: "plate",
  },
  {
    Slot: "Shoulders",
    Dungeon: "Mists of Tirna Scithe",
    BIS: false,
    class: "plate",
  },
  {
    Slot: "Shoulders",
    Dungeon: "The Necrotic Wake",
    BIS: false,
    class: "plate",
  },
  {
    Slot: "Shoulders",
    Dungeon: "Grim Batol",
    BIS: true,
    class: "warrior",
  },
  {
    Slot: "Chest",
    Dungeon: "Ara-Kara, City of Echoes",
    BIS: true,
    class: "warrior",
  },
  {
    Slot: "Chest",
    Dungeon: "The Dawnbreaker",
    BIS: true,
    class: "DK",
  },
  {
    Slot: "Wrist",
    Dungeon: "City of Threads",
    BIS: true,
    class: "DK",
  },
  { Slot: "Wrist", Dungeon: "Grim Batol", BIS: true, class: "warrior" },
  {
    Slot: "Hands",
    Dungeon: "Ara-Kara, City of Echoes",
    BIS: false,
    class: "plate",
  },
  {
    Slot: "Hands",
    Dungeon: "The Stonevault",
    BIS: false,
    class: "plate",
  },
  {
    Slot: "Hands",
    Dungeon: "Mists of Tirna Scithe",
    BIS: true,
    class: "warrior",
  },
  {
    Slot: "Hands",
    Dungeon: "Siege of Boralus",
    BIS: true,
    class: "DK",
  },
  {
    Slot: "Waist",
    Dungeon: "The Dawnbreaker",
    BIS: false,
    class: "plate",
  },
  {
    Slot: "Waist",
    Dungeon: "The Stonevault",
    BIS: false,
    class: "plate",
  },
  {
    Slot: "Waist",
    Dungeon: "The Necrotic Wake",
    BIS: true,
    class: "warrior",
  },
  {
    Slot: "Waist",
    Dungeon: "Siege of Boralus",
    BIS: true,
    class: "DK",
  },
  { Slot: "Waist", Dungeon: "Grim Batol", BIS: false, class: "plate" },
  {
    Slot: "Legs",
    Dungeon: "City of Threads",
    BIS: false,
    class: "plate",
  },
  {
    Slot: "Legs",
    Dungeon: "The Stonevault",
    BIS: false,
    class: "plate",
  },
  {
    Slot: "Legs",
    Dungeon: "Mists of Tirna Scithe",
    BIS: true,
    class: "warrior",
  },
  {
    Slot: "Legs",
    Dungeon: "The Necrotic Wake",
    BIS: true,
    class: "DK",
  },
  {
    Slot: "Legs",
    Dungeon: "Siege of Boralus",
    BIS: false,
    class: "plate",
  },
  {
    Slot: "Feet",
    Dungeon: "City of Threads",
    BIS: true,
    class: "warrior",
  },
  {
    Slot: "Feet",
    Dungeon: "Siege of Boralus",
    BIS: true,
    class: "DK",
  },
];
